### ISSUE TITLE
daysPast / daysAhead (Fun with timezones)

### ISSUE THREAD

**Issue by dannoh** [fewieden/MMM-NHL#18]
I still don't think this code is correct
```
        const date = new Date();
        date.setDate(date.getDate() - this.config.daysInPast);
        const startDate = date.toISOString().slice(0, 10);
        date.setDate(date.getDate() + this.config.daysInPast + this.config.daysAhead);
        const endDate = date.toISOString().slice(0, 10);
```
daysInPast = 1
At 11pm UTC-5 January 25th this code will add a day to make it 26, but then convert it to UTC to make it 27.  So you jump 2 days instead of just 1

**Comment by fewieden** [comment]
@dannoh I assumed the start- and endDate query params are supposed to be in UTC timezone because the timestamp of the game start is returned in UTC timezone.

I took another look into an unofficial API documentation and made changes accordingly to the develop branch.

![dates](https://user-images.githubusercontent.com/9334168/105806642-a0ae8800-5fa4-11eb-8547-034de7e15df3.jpg)

Does this resolve your issue?

**Comment by dannoh** [comment]
Looks right.  I'm not running that code base or config anymore, but it appears to be correct now.

**Comment by fewieden** [comment]
Released the fix and new rollOver config
